name: pepddg
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy>=1.26
  - scipy>=1.11
  - pandas>=2.1
  - pyyaml>=6.0
  - pytest>=7.4
  - gemmi>=0.6
  - openmm>=8.0
  - pdbfixer>=1.9
  - pytorch>=2.0
  - pip>=23
  - pip:
      - -e .
