name: pepddg
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - numpy>=1.26
  - scipy>=1.11
  - pandas>=2.1
  - pyyaml>=6.0
  - matplotlib>=3.8
  - seaborn>=0.13
  - statsmodels>=0.14
  - tqdm>=4.66
  - openpyxl>=3.1            # for reading bpti_dms_heyne2021.xlsx
  - pytest>=7.4
  - pip>=23
  - pip:
      - freesasa>=2.2
      - gemmi>=0.6
